logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
    kafka: ERROR

spring:
  application:
    name: course-registration

  datasource:
    url: jdbc:mysql://localhost:3307/course_registration?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: courseapp
    password: courseapp123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: course-registration-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.coursera.course_registration.kafka.events"